// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MemorySharingAPI.Models;

public partial class AdView
{
    public int AdViewId { get; set; }

    public int? AdId { get; set; }

    public string ViewerId { get; set; }

    public DateTime? ViewDate { get; set; }

    public virtual Advertisement Ad { get; set; }

    public virtual User Viewer { get; set; }
}