// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MemorySharingAPI.Models;

public partial class Analytic
{
    public int AnalyticsId { get; set; }

    public int? MomentId { get; set; }

    public int? Views { get; set; }

    public int? Likes { get; set; }

    public int? Comments { get; set; }

    public int? Shares { get; set; }

    public DateTime? LastUpdated { get; set; }

    public virtual Moment Moment { get; set; }
}