// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MemorySharingAPI.Models;

public partial class Follower
{
    public string FollowerId { get; set; }

    public string FollowingId { get; set; }

    public DateTime? FollowDate { get; set; }

    public virtual User FollowerNavigation { get; set; }

    public virtual User Following { get; set; }
}