// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MemorySharingAPI.Models;

public partial class MomentView
{
    public int ViewId { get; set; }

    public int? MomentId { get; set; }

    public string ViewerId { get; set; }

    public DateTime? ViewDate { get; set; }

    public string Ipaddress { get; set; }

    public virtual Moment Moment { get; set; }

    public virtual User Viewer { get; set; }
}