// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MemorySharingAPI.Models;

public partial class Moment
{
    public int MomentId { get; set; }

    public string UserId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string MediaUrl { get; set; }

    public string MediaType { get; set; }

    public DateTime? CreatedAt { get; set; }

    public bool? IsPublic { get; set; }

    public DateTime? ExpiryDate { get; set; }

    public int? Views { get; set; }

    public int? Likes { get; set; }

    public bool? IsMemory { get; set; }

    public virtual ICollection<Analytic> Analytics { get; set; } = new List<Analytic>();

    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();

    public virtual ICollection<Like> LikesNavigation { get; set; } = new List<Like>();

    public virtual ICollection<MomentCategory> MomentCategories { get; set; } = new List<MomentCategory>();

    public virtual ICollection<MomentShare> MomentShares { get; set; } = new List<MomentShare>();

    public virtual ICollection<MomentTag> MomentTags { get; set; } = new List<MomentTag>();

    public virtual ICollection<MomentView> MomentViews { get; set; } = new List<MomentView>();

    public virtual ICollection<Report> Reports { get; set; } = new List<Report>();

    public virtual ICollection<SavedMoment> SavedMoments { get; set; } = new List<SavedMoment>();

    public virtual User User { get; set; }
}