// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MemorySharingAPI.Models;

public partial class MomentTag
{
    public int MomentTagId { get; set; }

    public int? MomentId { get; set; }

    public int? TagId { get; set; }

    public virtual Moment Moment { get; set; }

    public virtual Tag Tag { get; set; }
}