// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MemorySharingAPI.Models;

public partial class PurchasableView
{
    public int ViewPackageId { get; set; }

    public string PackageName { get; set; }

    public decimal? Price { get; set; }

    public int? ViewCount { get; set; }

    public DateTime? CreatedAt { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<UserViewPackage> UserViewPackages { get; set; } = new List<UserViewPackage>();
}