// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MemorySharingAPI.Models;

public partial class Report
{
    public int ReportId { get; set; }

    public int? MomentId { get; set; }

    public string ReporterId { get; set; }

    public string ReportContent { get; set; }

    public DateTime? ReportDate { get; set; }

    public string Status { get; set; }

    public virtual Moment Moment { get; set; }

    public virtual User Reporter { get; set; }
}