// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MemorySharingAPI.Models;

public partial class UserTheme
{
    public int UserThemeId { get; set; }

    public string UserId { get; set; }

    public int? ThemeId { get; set; }

    public DateTime? PurchasedAt { get; set; }

    public virtual Theme Theme { get; set; }

    public virtual User User { get; set; }
}