// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MemorySharingAPI.Models;

public partial class UserViewPackage
{
    public int UserViewPackageId { get; set; }

    public string UserId { get; set; }

    public int? ViewPackageId { get; set; }

    public DateTime? PurchasedAt { get; set; }

    public int? ViewsRemaining { get; set; }

    public virtual User User { get; set; }

    public virtual PurchasableView ViewPackage { get; set; }
}